### ISSUE TITLE
1mb-cli deploy does not work

### ISSUE THREAD

**Issue by paulolorenzobasilio** [1MB/1mb-cli#4]
https://forum.1mb.site/?t=1558779395075

> I did a fresh node install (node 10.15.3, npm 6.4.1, 1mb-cli 2.0.3, windows 8.1 x64) and for some reason, running 1mb-cli deploy does not do anything, it just displays "Deploying .... done", but no changes are made on my site at all. Manually sending an api post request or using the editor works, though, with no errors whatsoever.

**Comment by 0x15f** [comment]
Great find! I use the Vue deploy command so I didn't catch this. Thank you for submitting the PR.
